services:
  - type: web
    name: pdf-telegram-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: pdf-telegram-bot
          property: url
    autoDeploy: true
    healthCheckPath: /health
